version: "3.9"

services:

  api-deep-doc:
    container_name: api-deep-doc
    hostname: api-deep-doc
    build:
      context: ./api
      dockerfile: Dockerfile

  db-deep-doc:
    container_name: db-deep-doc
    hostname: db-deep-doc
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - deep-doc-data:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  deep-doc-data: