version: "3.9"

services:

  db-deep-doc:
    container_name: db
    hostname: db-deep-doc
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - deep-doc-data:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  api-deep-doc:
    container_name: api
    hostname: api-deep-doc
    build:
      context: ./api
      dockerfile: Dockerfile
    image: local/api-deep-doc
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=admin
      - DB_PWD=admin
    ports:
      - '80:80'
    volumes:
      - ./api/app:/code

volumes:
  deep-doc-data: